name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'jaredpalmer/formik'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
 
      - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
